name: Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting and Prettifying
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: observatory
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "17.1.0"
      - name: Install Dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier-check
